### PR TITLE
fix(port): raise new error

### LINKED ISSUE #95: Port: for `Access` type, the `LogicalBridge` list must have only one item. If not then we need to throw error

### PR DESCRIPTION
**Pull request by glimchb**
Fixes #95

Signed-off-by: Boris Glimcher <Boris.Glimcher@emc.com>

### CODE REVIEW

File: pkg/evpn/port.go [hunk 1]
```diff
@@ -51,6 +51,13 @@ func (s *Server) CreateBridgePort(_ context.Context, in *pb.CreateBridgePortRequ
 		log.Printf("Already existing BridgePort with id %v", in.BridgePort.Name)
 		return obj, nil
 	}
+	// for Access type, the LogicalBridge list must have only one item
```
Comment (mardim91) [inline pkg/evpn/port.go:54]: ok seems right to me
